window.CORTEX_TRANSLATIONS = {
  "nav_services": "Services",
  "nav_packages": "Plans",
  "nav_how": "How It Works",
  "nav_about": "About Us",
  "nav_contact": "Contact Us",
  "hero_tag": "Armenia's first operational SOC center",
  "hero_h1": "Your security - <em>24/7</em>",
  "hero_desc": "Remote video surveillance, AI-assisted threat detection, light-and-sound deterrence, loudspeaker intervention, and drone response in one integrated system designed to act when every second matters.",
  "hero_btn1": "Request a quote →",
  "hero_btn2": "View plans",
  "monitor_status": "Monitoring active",
  "ctrl_strobe": "Strobe",
  "ctrl_light": "Light",
  "ctrl_sound": "Audio",
  "ctrl_speaker": "Speaker",
  "ctrl_bell": "Siren",
  "alert1": "Site N12 - Monitoring active",
  "alert2": "CAM 03 - Event detected",
  "alert3": "Verification - in progress",
  "alert4": "Notification - sent",
  "alert5": "Authorized access - confirmed",
  "tick1": "24/7 remote monitoring",
  "tick2": "AI-assisted threat detection",
  "tick3": "Light-and-sound deterrence",
  "tick4": "Audio and loudspeaker deterrence",
  "tick5": "Drone-based response and information gathering",
  "tick6": "Secure data storage and retention",
  "tick7": "SLA response",
  "tick8": "Coordination with law enforcement",
  "tick9": "Vanadzor · Armenia",
  "stat1": "Monitoring",
  "stat2": "Detection",
  "stat3": "Classification",
  "stat4": "SLA response",
  "prob_eyebrow": "Problem Analysis",
  "prob_h2": "What is wrong with the conventional security model",
  "p1t": "No one is watching in real time",
  "p1d": "A DVR/NVR may simply record footage, but in many cases no one is actively supervising the situation in real time.",
  "p2t": "Delayed response",
  "p2d": "When response begins only after the event, it is often already too late.",
  "p3t": "Loss of evidence",
  "p3d": "Local storage can be damaged or destroyed, while cloud retention significantly reduces that risk.",
  "vs_old": "Conventional approach",
  "vs_new": "Cortex Sentinel",
  "vs1b": "No active monitoring",
  "vs1g": "24/7 live monitoring",
  "vs2b": "Local DVR/NVR - vulnerable",
  "vs2g": "Cloud retention - 7-90 days",
  "vs3b": "Delayed response",
  "vs3g": "SLA - up to 2 minutes",
  "vs4b": "False alarms",
  "vs4g": "AI + operator analysis",
  "vs5b": "No deterrence",
  "vs5g": "Light · sound · loudspeaker · drone",
  "svc_eyebrow": "Services",
  "svc_h2": "A complete security ecosystem",
  "svc_desc": "One platform covering the entire security chain - from detection to response.",
  "s1n": "24/7 remote monitoring",
  "s1d": "Our SOC operators monitor video streams around the clock and assess risks in real time.",
  "s1t": "12 / 6 / 3 / 1 months",
  "s2n": "AI support",
  "s2d": "Algorithmic analysis, suspicious movement detection, and automatic classification - within seconds.",
  "s2t": "Included in all packages",
  "s3n": "Notification and response",
  "s3d": "For Class A events, rapid notification is sent by phone, SMS, or any agreed communication channel.",
  "s3t": "Under SLA terms",
  "s4n": "Loudspeaker intervention",
  "s4d": "A live or pre-recorded voice message used to deter intrusion and instruct people on site.",
  "s4t": "Optional / depends on plan",
  "s5n": "Drone response",
  "s5d": "In selected cases, aerial observation and additional video capture are available.",
  "s5t": "Optional service",
  "s6n": "Video logging and retention",
  "s6d": "Cloud retention from 7 to 90 days, with rapid access and the possibility of using the material as evidence.",
  "s6t": "Included in all packages",
  "how_eyebrow": "Process",
  "how_h2": "How we work",
  "how_desc": "From onboarding to full protection - in four clear steps.",
  "pkg_common_title": "Included in every plan",
  "pkg_common_1": "24/7 monitoring",
  "pkg_common_2": "AI-assisted detection",
  "pkg_common_3": "Light-and-sound deterrence",
  "pkg_common_4": "Alerts and escalation",
  "pkg_common_5": "7-day retention",
  "pkg1u1": "Lowest monthly cost",
  "pkg1u2": "Best for long-term sites",
  "pkg1u3": "All optional response layers available",
  "pkg2u1": "Best balance of price and term",
  "pkg2u2": "Suitable for active business sites",
  "pkg2u3": "Additional response layers added as needed",
  "pkg3u1": "Flexible short-term option",
  "pkg3u2": "Suitable for seasonal or pilot phases",
  "pkg3u3": "All add-ons are connected separately",
  "pkg4u1": "Most flexible starting option",
  "pkg4u2": "Suitable for rapid launch or pilot phase",
  "pkg4u3": "Can be extended easily later",
  "step1n": "Connection",
  "step1d": "We connect and integrate your surveillance infrastructure - cameras, recorders, and network equipment.",
  "step2n": "Configuration",
  "step2d": "We define monitoring zones, notification channels, verification rules, and response conditions.",
  "step3n": "Monitoring",
  "step3d": "The SOC center operates 24/7, AI identifies risks, and the operator analyzes and classifies them.",
  "step4n": "Response",
  "step4d": "A multi-level response process including notification, deterrence, additional actions, and an incident report.",
  "pkg_eyebrow": "Pricing",
  "pkg_h2": "Subscription plans",
  "pkg_desc": "All prices are listed in AMD, per camera, per month.",
  "pkg_popular": "Most popular",
  "pkg_percam": "1 camera / month",
  "pkg1n": "12-month plan",
  "pkg1f1": "24/7 remote monitoring",
  "pkg1f2": "Event detection and verification",
  "pkg1f3": "Notifications (phone call / SMS / messenger)",
  "pkg1f4": "Light-and-sound deterrence",
  "pkg1f5": "7-day video retention",
  "pkg1f6": "Backup power (UPS) - optional",
  "pkg1f7": "Backup internet connection - optional",
  "pkg1btn": "Choose 12 months →",
  "pkg2n": "6-month plan",
  "pkg2f1": "24/7 remote monitoring",
  "pkg2f2": "Event detection and verification",
  "pkg2f3": "Light-and-sound deterrence",
  "pkg2f4": "Notifications (phone call / SMS / messenger)",
  "pkg2f5": "Police alert escalation",
  "pkg2btn": "Choose 6 months →",
  "pkg3n": "3-month plan",
  "pkg3f1": "24/7 remote monitoring",
  "pkg3f2": "Event detection and verification",
  "pkg3f3": "Light-and-sound deterrence",
  "pkg3f4": "Notifications (phone call / SMS / messenger)",
  "pkg3f5": "Police alert escalation",
  "pkg3btn": "Choose 3 months →",
  "pkg4n": "1-month plan",
  "pkg4f1": "24/7 remote monitoring",
  "pkg4f2": "Event detection and verification",
  "pkg4f3": "Light-and-sound deterrence",
  "pkg4f4": "Notifications (phone call / SMS / messenger)",
  "pkg4f5": "Police alert escalation",
  "pkg4btn": "Choose 1 month →",
  "opt_eyebrow": "Additional options",
  "opt_lead": "Optional capabilities that improve reliability, deterrence, and storage flexibility.",
  "opt1tag": "Reliability",
  "opt1n": "Backup power (UPS)",
  "opt1d": "Keeps the system operational during a power outage.",
  "opt2tag": "Connectivity",
  "opt2n": "Backup 4G internet",
  "opt2d": "If the primary internet connection fails, the system can switch to mobile connectivity.",
  "opt3tag": "Deterrence",
  "opt3n": "Loudspeaker intervention",
  "opt3d": "A live operator voice message for preventive intervention on site.",
  "opt4tag": "Response",
  "opt4n": "Drone response",
  "opt4d": "Aerial observation and rapid video capture when required.",
  "opt5tag": "Retention",
  "opt5n": "Additional storage days",
  "opt5d": "The base package includes 7 days. Each extra day costs 700 AMD per day, per camera.",
  "opt6tag": "Flexibility",
  "opt6n": "Flexible extension",
  "opt6d": "You can define retention as 7+1, 7+2, 7+3, and so on, according to your needs.",
  "calc_title": "Custom calculator - build your plan",
  "calc_cams": "Number of cameras",
  "calc_period": "Subscription term",
  "p12": "12 months",
  "p6": "6 months",
  "p3": "3 months",
  "p1": "1 month",
  "calc_storage": "Video retention",
  "calc_storagenote": "The base package includes 7 days. Each extra day costs 700 AMD per day, per camera.",
  "calc_extradays": "Additional days",
  "calc_total": "Total",
  "calc_addons": "Additional options",
  "calc_per_cam": "Monthly rate - 1 camera",
  "calc_unit": "AMD / month / camera",
  "calc_monthly": "Monthly total",
  "calc_cta": "Contact us →",
  "why_eyebrow": "Why Cortex Sentinel",
  "why_eyebrow_prefix": "Why",
  "why_h2": "Armenia's first operational remote SOC center",
  "why_desc": "",
  "why_note": "The service is structured within a clear operational and contractual framework: monitoring zones, response rules, retention, escalation, and reporting.",
  "why_sum1k": "response",
  "why_sum1d": "Average response time is based on SLA logic and a predefined escalation path.",
  "why_sum2k": "retention",
  "why_sum2d": "Recordings and incident materials are retained under the contractual framework and remain available for export.",
  "why_sum3k": "verification",
  "why_sum3d": "Each alert is first verified and classified before it enters the full response chain.",
  "w1t": "Security as a Service",
  "w1m": "24/7 SOC",
  "w1d": "The service operates on a subscription model, without heavy capital expenditure or operational burden on the client.",
  "w3t": "AI + operator + verification",
  "w3m": "A / B / C class",
  "w3d": "AI identifies risk, while the operator verifies and classifies the event to reduce false alerts and accelerate real response.",
  "w5t": "Notification and escalation",
  "w5m": "call / SMS / police",
  "w5d": "Notification order, authorized contacts, and external escalation are defined in advance and follow one clear scenario.",
  "m4": "Average response time",
  "soc_panel_kicker": "How a real SOC operates",
  "soc_s1t": "Detection",
  "soc_s1d": "The video stream is monitored 24/7, while AI and the operator identify suspicious movement, intrusion, or technical deviations.",
  "soc_s1m": "24/7 monitoring + AI",
  "soc_s2t": "Verification",
  "soc_s2d": "The operator reviews the video, determines whether the event is real or false, and classifies it by priority.",
  "soc_s2m": "A / B / C class",
  "soc_s3t": "Response",
  "soc_s3d": "A pre-agreed response chain is activated: phone call, SMS, loudspeaker, light-and-sound deterrence, or escalation when required.",
  "soc_s3m": "SLA + escalation",
  "soc_s4t": "Retention and reporting",
  "soc_s4d": "Video, stills, and the action history are retained under the contractual framework and remain available for later use.",
  "soc_s4m": "7-90 days / export",
  "soc_outcome_t": "Outcome",
  "soc_outcome_s": "one unified chain",
  "soc_outcome_d": "The client receives more than recording: detection, verification, response, and preservation of the full incident history within one service.",
  "cf_eyebrow": "Get in touch",
  "cf_title": "Write to us - <span>response within 24 hours</span>",
  "cf_desc": "Monitoring, pricing, site assessment, and direct contact - with a fast response.",
  "cf_phone_lbl": "Phone",
  "cf_email_lbl": "Email",
  "cf_addr_lbl": "Address",
  "cf_addr": "Armenia, Vanadzor, 29-19 Tigran Mets",
  "form_title": "Send a request",
  "form_sub": "Fill in the fields and we will contact you.",
  "form_name": "Full name *",
  "form_name_ph": "John Smith",
  "form_phone": "Phone *",
  "form_cams": "Number of cameras",
  "form_sub_label": "Subscription",
  "form_obj": "Facility / area",
  "form_msg": "Message (optional)",
  "form_msg_ph": "Write a comment",
  "form_help": "After filling in your name and phone number, the request delivery options will appear below. If it is more convenient, you can call the listed phone number directly.",
  "form_submit": "Send request →",
  "form_ready_title": "Choose how you want to contact us",
  "form_ready_text": "You can send the request via WhatsApp, by email, or call us directly.",
  "form_action_whatsapp": "Open WhatsApp",
  "form_action_email": "Open Email",
  "form_action_call": "Call now",
  "form_error_title": "Check the form",
  "form_error_required": "Please fill in your name and phone number.",
  "form_error_phone": "Please enter a valid phone number.",
  "form_error_email": "Please enter a valid email address or leave the field empty.",
  "sel_choose": "-- Select --",
  "obj1": "Office",
  "obj2": "Shop",
  "obj3": "Warehouse",
  "obj4": "Open area",
  "obj5": "Residential house",
  "obj6": "Other",
  "form_ok_title": "Request received",
  "form_ok_text": "Thank you. We will contact you shortly. +374 98 77 00 98",
  "cta_eyebrow": "Get in touch",
  "cta_h2": "Ready for<br/>real security?",
  "cta_desc": "Free consultation, site assessment, and guidance in selecting the right package.",
  "footer_desc": "Cortex Sentinel LLC - remote video surveillance, 24/7 monitoring, AI analysis, response, and video retention.",
  "footer_quick_title": "Quick links",
  "footer_link_calculator": "Custom calculator",
  "footer_service_light": "Strobe and siren response",
  "contact_unified_address": "Armenia, Lori Province, Vanadzor, 29-19 Tigran Mets - TIN 06978495",
  "contact_unified_desc": "Free consultation, site assessment, and support in selecting the right package.",
  "contact_unified_title": "Ready for real security?",
  "stat5": "Uptime guarantee",
  "pkg1f8": "Loudspeaker response - optional",
  "pkg1f9": "Drone response - optional",
  "pkg1f10": "Police alert escalation",
  "pkg1f11": "Additional video retention - optional",
  "pkg2f6": "Loudspeaker response - optional",
  "pkg2f7": "Drone response - optional",
  "pkg2f8": "7-day video retention",
  "pkg2f9": "Backup power (UPS) - optional",
  "pkg2f10": "Backup internet connection - optional",
  "pkg2f11": "Additional video retention - optional",
  "pkg3f6": "Loudspeaker response - optional",
  "pkg3f7": "Drone response - optional",
  "pkg3f8": "7-day video retention",
  "pkg3f9": "Backup power (UPS) - optional",
  "pkg3f10": "Backup internet connection - optional",
  "pkg3f11": "Additional video retention - optional",
  "pkg4f6": "Loudspeaker response - optional",
  "pkg4f7": "Drone response - optional",
  "pkg4f8": "7-day video retention",
  "pkg4f9": "Backup power (UPS) - optional",
  "pkg4f10": "Backup internet connection - optional",
  "pkg4f11": "Additional video retention - optional"
};

Object.assign(window.CORTEX_TRANSLATIONS, {
  "nav_packages": "Subscription",
  "hero_tag": "Armenia's first real SOC",
  "hero_desc": "Remote video surveillance, AI-enabled threat detection, light-and-sound, loudspeaker, and drone response in one integrated system that acts precisely when every second matters.",
  "hero_btn1": "Start for free →",
  "hero_btn2": "View packages",
  "alert2": "CAM 03 - event detected",
  "tick2": "Threat detection with AI support",
  "tick4": "Audio / loudspeaker deterrence",
  "tick5": "Drone-based deterrence and information gathering",
  "tick6": "Secure and protected data retention",
  "tick9": "Armenia · Yerevan · Vanadzor",
  "stat4": "SLA · response",
  "stat5": "\"UPTIME\" guarantee",
  "prob_eyebrow": "Problems",
  "prob_h2": "Why standard security systems fail",
  "p1d": "A camera may record footage, but no one is watching it in real time.",
  "p2d": "If response begins only after the event, it is often already late.",
  "p3d": "Local storage can fail, be tampered with, or be lost.",
  "svc_desc": "One platform that brings together detection, verification, notification, and rapid response.",
  "s1t": "12 months · 6 months · 3 months · 1 month",
  "s2d": "With AI support, the system captures the event for rapid assessment and response.",
  "s3n": "Response, notification, and alerting",
  "s3d": "Rapid verification, response, notification, and alerting based on a clear scenario.",
  "s4n": "Loudspeaker response",
  "s4d": "Live or pre-recorded voice message.",
  "s4t": "Optional service",
  "s5d": "Aerial monitoring and additional video capture to keep the event under control.",
  "s6d": "Retention of recordings for 7 to 90 days for later analysis.",
  "s6t": "Included in all packages · Optional",
  "how_desc": "From system launch to full protection — in 4 clear steps.",
  "step1n": "Integration",
  "step1d": "We connect cameras, the network, and the feeds.",
  "step2d": "We define and agree the zones and rules.",
  "step3d": "24/7 control with AI support and operator oversight.",
  "step4d": "Deterrence, notification, alerting, and reporting.",
  "pkg_desc": "All prices are in AMD, VAT included · per month · per camera.",
  "pkg_common_title": "Included by default in all packages",
  "pkg_common_4": "Notification and alerting",
  "pkg1u1": "For long-term cooperation, this provides the most advantageous monthly rate.",
  "pkg1u2": "24/7 monitoring, AI support, and light-and-sound deterrence are included by default.",
  "pkg1u3": "Notification, alerting, and 7-day retention are included, while the remaining services are available as options.",
  "pkg2u1": "A suitable option when you need to combine a favorable rate with a shorter contract term.",
  "pkg2u2": "24/7 monitoring, AI support, and light-and-sound deterrence are included by default.",
  "pkg2u3": "Notification, alerting, and 7-day retention are included, while the remaining services are available as options.",
  "pkg3u1": "Designed for seasonal, temporary, or short-term sites.",
  "pkg3u2": "24/7 monitoring, AI support, and light-and-sound deterrence are included by default.",
  "pkg3u3": "Notification, alerting, and 7-day retention are included, while the remaining services are available as options.",
  "pkg4u1": "Suitable for a rapid launch, a trial period, or a short-term need.",
  "pkg4u2": "24/7 monitoring, AI support, and light-and-sound deterrence are included by default.",
  "pkg4u3": "Notification, alerting, and 7-day retention are included, while the remaining services are available as options.",
  "opt_eyebrow": "Additional optional services",
  "opt_lead": "Optional features that improve system reliability, uninterrupted monitoring, event detection, and incident prevention.",
  "opt2n": "Backup internet connection (4G/5G)",
  "opt5n": "Additional video retention",
  "opt6d": "Video retention can be set up to 90 days.",
  "calc_title": "Custom calculator — build your package",
  "calc_storagenote": "7 days are included by default. Each additional day: AMD 700 / day / camera.",
  "calc_addons": "Additional services",
  "calc_per_cam": "Monthly cost per camera (AMD / month / camera)",
  "calc_monthly": "Monthly total:",
  "calc_cta": "Order → Contact us",
  "why_h2": "Armenia's first real SOC",
  "why_note": "The service is organized and delivered within clearly defined operational and legal boundaries, including monitoring-zone definition, response and prevention mechanisms, notification and alerting procedures, data-retention rules, and accountability.",
  "why_sum1d": "Fast response under the SLA",
  "why_sum2d": "Retention for up to 90 days",
  "why_sum3d": "Assessment, classification, response",
  "w1t": "Security-as-a-Service",
  "w1d": "A subscription service without major upfront costs.",
  "w3t": "AI + operator",
  "w3d": "With AI support, the system captures the event while the operator assesses, classifies, and responds.",
  "w5d": "Based on a predefined scenario, the system places a call, sends a short message, or escalates.",
  "m4": "Average response",
  "soc_panel_kicker": "How a real SOC works",
  "soc_s1d": "24/7 monitoring and AI-assisted capture.",
  "soc_s1m": "24/7 monitoring + AI",
  "soc_s2d": "The event is checked, assessed, and classified.",
  "soc_s3d": "A light-and-sound signal, loudspeaker and drone response, a call, and an alert are triggered.",
  "soc_s3m": "SLA + response",
  "soc_s4d": "Recordings and event logs are retained and can be exported.",
  "soc_outcome_d": "Not just recording, but detection, verification, assessment, response, and prevention.",
  "cf_desc": "Monitoring, pricing, site assessment, and direct contact with a fast response.",
  "form_action_email": "Open E-mail",
  "sel_choose": "— Select —",
  "form_ok_text": "Thank you. We will contact you soon. +374 98 77 00 98",
  "cta_h2": "Ready to get<br/>real security?",
  "cta_desc": "Free consultation, site assessment, and help choosing the right package.",
  "footer_desc": "Cortex Sentinel LLC — remote video surveillance, 24/7 monitoring, AI analytics, response, and video retention.",
  "contact_unified_address": "Registered address: 29-19 Tigran Mets, Vanadzor, Armenia · Operations across all of Armenia · TIN 06978495",
  "contact_unified_desc": "Free consultation, site or area assessment, and guidance in choosing the right package.",
  "contact_unified_title": "Ready to get real security?",
  "pkg1f10": "Police alert",
  "pkg2f5": "Police alert",
  "pkg3f5": "Police alert",
  "pkg4f5": "Police alert"
});
Object.assign(window.CORTEX_TRANSLATIONS, {
  "hero_tag": "Armenia's first real SOC",
  "contact_hub_kicker": "LIVE CHAT + WHATSAPP/TELEGRAM/FACEBOOK",
  "contact_hub_text": "",
  "contact_hub_live_title": "Live Chat",
  "contact_hub_live_meta": "",
  "contact_hub_whatsapp_title": "WhatsApp",
  "contact_hub_whatsapp_meta": "",
  "contact_hub_email": "Email",
  "contact_hub_call": "Call",
  "contact_hub_form": "Form",
  "contact_hub_greeting_title": "Cortex Sentinel manager",
  "contact_hub_greeting_text": "Hello, may I help you with something?",
  "contact_hub_greeting_close": "Close",
  "s1d": "Our SOC operators monitor streams 24/7<br/>and assess risks.",
  "s2d": "AI support captures the event<br/>for rapid assessment and response.",
  "s3d": "Rapid verification, response,<br/>notification, and alerting.",
  "s4d": "Live or pre-recorded<br/>voice message.",
  "s5d": "Aerial monitoring and extra video capture<br/>to keep control.",
  "s6d": "Retention of recordings for 7 to 90 days<br/>for later analysis.",
  "step1d": "We connect cameras,<br/>the network, and the<br/>feeds.",
  "step2d": "We define and approve<br/>the zones and<br/>rules.",
  "step3d": "24/7 control with AI<br/>and operator<br/>oversight.",
  "step4d": "Deterrence,<br/>notification, alerting,<br/>and reporting.",
  "opt2n": "Backup internet (4G/5G)",
  "calc_storagenote": "The base plan includes 7 days.<br/>Each extra day costs 700 AMD / day / camera.",
  "opt5d": "The base plan includes 7 days.<br/>Each extra day costs 700 AMD / day / camera.",
  "footer_desc": "Cortex Sentinel LLC — remote video surveillance, 24/7 monitoring, AI analytics, response, and video retention"
});
